apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: klovercloud-letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: support@klovercloud.com
    privateKeySecretRef:
      name: klovercloud-letsencrypt-key
    solvers:
      - http01:
          ingress:
            class: nginx