apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: klovercloud-operator-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: klovercloud-operator-cr
subjects:
  - kind: ServiceAccount
    name: klovercloud-operator-sa
    namespace: klovercloud