apiVersion: apps/v1
kind: Deployment
metadata:
  name: klovercloud-operator
  namespace: klovercloud
  labels:
    control-plane: klovercloud-operator
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      control-plane: klovercloud-operator
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        control-plane: klovercloud-operator
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
        - command:
            - /home/klovercloud/app/manager
          envFrom:
            - secretRef:
                name: klovercloud-operator-secret
            - configMapRef:
                name: klovercloud-operator-cm
          args:
            - "--leader-elect"
          image: quay.io/klovercloud/klovercloud-operator:v1.0.0
          imagePullPolicy: Always
          name: manager
          resources:
            limits:
              cpu: "200m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
      serviceAccountName: klovercloud-operator-sa
      terminationGracePeriodSeconds: 10