apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: default-istio-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*.<istio-domain>'
      port:
        name: http
        number: 80
        protocol: HTTP
