apiVersion: v1
kind: Pod
metadata:
  name: temporal-db-setup
spec:
  restartPolicy: Never
  containers:
    - name: setup-runner
      image: quay.io/klovercloud/temporal-postgres-setup-runner:v0.2
      imagePullPolicy: Always
      command: ["/bin/bash", "-c", "bash /scripts/temporal-db-setup.sh"]
      env:
        - name: SQL_HOST
          value: postgres-cluster-rw.temporal.svc.cluster.local
        - name: SQL_PORT
          value: "5432"
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
      volumeMounts:
        - name: script-volume
          mountPath: /scripts
  volumes:
    - name: script-volume
      configMap:
        name: temporal-db-setup-script
        defaultMode: 0775