---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: gitlab-server
  name: gitlab-data
  namespace: gitlab
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
